[package]
name = "dlpack-rs"
description="Rust bindings for the DLPack protocol"
version = "0.1.0"
license="Apache-2.0"
edition = "2021"
build = "build.rs"


[build-dependencies]
bindgen = ">=0.60.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
