[package]
name = "dlpack-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[build-dependencies]
bindgen = "*"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
