# from: https://github.com/strasdat/vviz/blob/main/.github/workflows/ci.yml
name: Continuous integration

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git Sumbodule Update
        run: |
          git submodule update --init --recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dlpack.rs
          file_pattern: dlpack.rs
      - name: "Cargo test"
        run: cargo test
      - name: "Cargo package"
        run: cargo package --no-verify
      - run: cargo publish --no-verify --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
